Avoid the str() constructor
Do not force string representations of stuff using the str() constructor
because in almost all cases it is unnecessary and can cause funky
encoding problems, most notably the notorious:

UnicodeEncodeError: 'ascii' codec can't encode character '\ua000' in
  position 0: ordinal not in range(128)

Instead, rely on python to convert the input object to the required
target type, oblivious of the actual type until we do input/output.