testsuite: Fix config parser test for recent python
python3.8 on Ubuntu 20.08 throws the following error on our config
parser test:

ValueError: Invalid format 'format%(foo1)' for '%' style

This is due to an incomplete log format string which seems to have been
acceptable to python3.5 on Ubuntu 18.04 before.

Make it a proper format string to avoid the error.