Handles deprecation warnings in unit tests with python3 (#99)
* Removes DeprecationWarning in unittests with python3

DeprecationWarning: Please use assertRaisesRegex instead is due to
a change in python where funcitons have been renamed. But not in
earlier versions. This commit introdues a change in handling
python2 and python3 differently with those functions.

* Fix AttributeError

'IdentifierMissingException' object has no attribute 'message' in ruleset.py