rules: Catch invalid evaluation results
If a rule was missing an implication to a rule result, we would throw an
exception such as:

Traceback (most recent call last):
  File "peekaboo/ruleset/engine.py", line 120, in run
    sample.add_rule_result(result)
  File "peekaboo/sample.py", line 298, in add_rule_result
    self.__report.append(_("File \"%s\": %s") % (self.__filename, res))
  File "peekaboo/ruleset/__init__.py", line 69, in __str__
    % (self.result.name, self.rule, self.reason,
AttributeError: 'bool' object has no attribute 'name'

Catch those invalid evaluation results, log a warning and abort
evaluation with result failed.