Fix integer division for python3
python3 says:

TypeError: 'float' object cannot be interpreted as an integer

because division always returns a float there but range() expects an
integer. Use // for explicit integer division to work around that.