ruleset: Fix refactoring fallout
Refactoring in commit 160ebc6b introduced Rule.get_cuckoo_report() which
would normally return a report object or None. There was one error path
though, in which it would return a RuleResult. Commit 9e5a10a2 fixed
this for ExpressionRule but not the CuckooRules. This would lead to
NoneType exceptions if submit to cuckoo failed:

2019-12-20 12:51:00,817 - peekaboo.ruleset.engine - (Worker-2) - ERROR -
'NoneType' object has no attribute 'signatures'
Traceback (most recent call last):
  File "peekaboo/ruleset/engine.py", line 136, in __exec_rule
    result = rule.evaluate(sample)
  File "peekaboo/ruleset/rules.py", line 337, in evaluate
    return self.evaluate_report(report)
  File "peekaboo/ruleset/rules.py", line 368, in evaluate_report
    for descr in report.signatures:
AttributeError: 'NoneType' object has no attribute 'signatures'

Handle None return of get_cuckoo_report() in CuckooRule.evaluate().
Explicitly compare to None to avoid cases where for whatever reason a
valid report would evaluate as False. Move the message content comment
to where the message is now generated.